### ISSUE TITLE
Analyse Solidity code with Slither and Mythril

### ISSUE THREAD

**Issue by leovct** [Everest-Option-Exchange-Team/contracts#12]
## Motivation
Smart contracts are often exploited and we should strive to write safe code. Here's a great [article](https://soliditydeveloper.com/smart-contract-security-analyzers) to understand the world of automated smart contract analyzers. The takeaway from this article is that analyzers do not replace an audit at all but they are useful to detect vulnerabilities. Many tools exist (9 tools are listed in the article) but when combining all of them, only 42% of all vulnerabilities could be detected (the author performed test benchmarking). Here's what the author says, "the combination of Mythril and Slither allows detecting a total of 42/115 (37%) vulnerabilities, which is the best trade-off between accuracy and execution costs". That's why we should integrate slither and mythril in our ci workflow.

**Slither** is a tool that is used by many big players in the web3 industry to perform static analysis on our solidity code.\
> Slither is a Solidity static analysis framework written in Python 3. It runs a suite of vulnerability detectors, prints visual information about contract details, and provides an API to easily write custom analyses. Slither enables developers to find vulnerabilities, enhance their code comprehension, and quickly prototype custom analyses.
Source: https://github.com/crytic/slither

**Mythril** is another security analysis tool for EVM bytecode.
> It detects security vulnerabilities in smart contracts built for Ethereum, Hedera, Quorum, Vechain, Roostock, Tron and other EVM-compatible blockchains. It uses symbolic execution, SMT solving and taint analysis to detect a variety of security vulnerabilities. It's also used (in combination with other tools and techniques) in the [MythX](https://mythx.io/) security analysis platform.
Source: https://github.com/ConsenSys/mythril

## Tasks
- [x] Integrate slither in our CI workflow
- [x] Fix warnings raised by running slither on our code
- [x] Integrate mythril in our CI workflow
- [x] Fix warnings raised by running mythril on our code
