### ISSUE TITLE
Write an ERC20 token factory contract

### ISSUE THREAD

**Issue by leovct** [Everest-Option-Exchange-Team/contracts#22]
## Motivation
We want to be able to create and deploy ERC20-like contracts. This will then allow us to create a set of contracts that represent synthetic assets (like mirror.finance with mAAPL, mABNB etc.).

We should specify the `name` and the `symbol` of the ERC20 token as well as two addresses, `minterAddress` and `pauserAddress`. The first address can mint tokens and the second one can pause transfers. The token should be burnable.

Inspiration: https://docs.umaproject.org/contracts/financial-templates/common/TokenFactory

## Tasks
- [ ] Implement the contract.
- [ ] Write tests.
- [ ] Deploy it on Fuji testnet.
- [ ] Test its behaviour.
