### ISSUE TITLE
Write a contract that fetches the price of a stock asset

### ISSUE THREAD

**Issue by leovct** [Everest-Option-Exchange-Team/contracts#23]
## Motivation
We want to create mirrored assets thus we need to get stock assets prices in real time.

To do this, we can use Chainlink Data Feeds. The only problem is that they don't provide stock asset prices straight out of the box, only crypto asset prices. That's why we need to use what they call **External Adapters**. Basically, an external adapter is like a custom API living on Chainlink nodes and it exposes any information (like stock prices). Alpha Vantage is one of them, they provide stock and crypto data API and it is hosted by Chainlink nodes so we can call it like we would do for any other data feed provided by Chainlink. Here's an article on the subject: https://blog.chain.link/build-and-use-external-adapters/

Here's the code sample to request TSLA stock price using Alpha Vantage external adapter:
```solidity
bytes32 jobId =  “802ec94e00184b789a016b8e71ae9fb4”;
address oracle =  0x56dd6586DB0D08c6Ce7B2f2805af28616E082455;

function requestTSLAPrice() public {
    Chainlink.Request memory req = buildChainlinkRequest(jobId, address(this), this.fulfillEthereumPrice.selector);
    req.add("function", "GLOBAL_QUOTE");
    req.add("symbol", "TSLA");
    string[] memory copyPath = new string[](2);
    copyPath[0] = "Global Quote";
    copyPath[1] = "05. price";
    req.addStringArray("copyPath", copyPath);
    req.addInt("times", 100000000);
    sendChainlinkRequestTo(oracle, req, fee);
}
```

## Tasks
- [x] Implement a contract that can request any stock asset price provided by Alpha Vantage external adapter.
- [x] Write tests.
- [x] Deploy it on Fuji testnet.
- [x] Test its behaviour.
