### ISSUE TITLE
Change require to revert with custom Error

### ISSUE THREAD

**Issue by yvesbou** [Everest-Option-Exchange-Team/contracts#38]
# Motivation
We want to further optimise our smart contracts. They should be gas efficient.  This [article](https://blog.soliditylang.org/2021/04/21/custom-errors/) talks about using revert statements instead of require statements to save gas costs.

## Todo:
- [ ] Write Custom Errors
- [ ] revert with Custom Errors
- [ ] adapt our Tests

## Resources
- https://blog.soliditylang.org/2021/04/21/custom-errors/
- Example: https://github.com/paulrberg/prb-contracts/blob/923f3150625427dc79bbb1a100e50ad0007c33b7/contracts/token/erc20/ERC20.sol
