### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by leovct** [Everest-Option-Exchange-Team/contracts#7]
# Motivation
Methods defined in our smart contracts should come with tests. **This is mandatory!**

Here are the tools we should use: [hardhat](https://hardhat.org/guides/waffle-testing.html) and [foundry](https://github.com/gakonst/foundry).

With the first one, you can write tests in javascript while with the second one, you write tests in solidity. Both are standards in the web3 industry. More information on Foundry: https://www.paradigm.xyz/2021/12/introducing-the-foundry-ethereum-development-toolbox

# Tasks
- [x] Write`fund()` tests.
- [x] Write `withdraw()` tests.
- [x] Write `getFunders()` tests.
- [x] Write `getTotalFunds()` tests.
