### ISSUE TITLE
Withdraw custom amount from the fund

### ISSUE THREAD

**Issue by leovct** [Everest-Option-Exchange-Team/contracts#9]
## Motivation
Users should be able to withdraw custom amounts from the fund and not only all the funds deposited.

## Tasks
- [x] Enable to withdraw custom amounts from the fund.
- [x] Update the current tests.
- [x] Write new tests for this new feature.
